name: Test Angular App

on: [push]

jobs:
  test:
    name: Test on node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node: [10, 12]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Use node ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          registry-url: https://registry.npmjs.org
      - name: install
        run: npm install
      - name: install-webdriver-manager
        run: npm install -g protractor  
      - name: update-chrome-driver-version
        run: webdriver-manager update --versions.chrome 84.0.4147.30  
      - name: e2e-test
        run: npm run e2e --protractor-config=e2e/protractor-ci.conf.js