name: Test Angular App

on: [push]

jobs:
  test:
    name: Test on node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node: [10.x]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Use node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
          registry-url: https://registry.npmjs.org
      - name: install
        run: npm install
      - name: unit-test
        run: npm run test --browsers=ChromeHeadless --watch=false --code-coverage
      - name: e2e-test
        run: npm run e2e --protractor-config=e2e/protractor-ci.conf.js --browsers=ChromeHeadless --watch=false --code-coverage